// <auto-generated />
using System;
using CareGardenApiV1.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareGardenApiV1.Migrations
{
    [DbContext(typeof(CareGardenApiDbContext))]
    [Migration("20230708154436_CareGardenV4")]
    partial class CareGardenV4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareGardenApiV1.Model.Appointment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("userId", "businessId", "date", "status");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Business", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("appointmentPeopleCount")
                        .HasColumnType("integer");

                    b.Property<int>("appointmentTimeInterval")
                        .HasColumnType("integer");

                    b.Property<string>("city")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("descriptionEn")
                        .HasColumnType("text");

                    b.Property<int>("discountRate")
                        .HasColumnType("integer");

                    b.Property<string>("district")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<double>("latitude")
                        .HasColumnType("double precision");

                    b.Property<Point>("location")
                        .HasColumnType("geometry");

                    b.Property<double>("longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("nameEn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("officialHolidayAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("password")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("province")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("updateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("verified")
                        .HasColumnType("boolean");

                    b.Property<int>("workingDayType")
                        .HasColumnType("integer");

                    b.Property<string>("workingEndHour")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("workingGenderType")
                        .HasColumnType("integer");

                    b.Property<string>("workingStartHour")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("id");

                    b.HasIndex("email", "telephone", "city");

                    b.ToTable("Business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.BusinessGallery", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<string>("imageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("isProfilePhoto")
                        .HasColumnType("boolean");

                    b.Property<string>("size")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.ToTable("BusinessGallery");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.BusinessProperties", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<string>("key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("value")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.ToTable("BusinessProperties");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.BusinessServiceModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("serviceId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("serviceId");

                    b.ToTable("BusinessService");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.BusinessWorkingInfo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("appointmentPeopleCount")
                        .HasColumnType("integer");

                    b.Property<int>("appointmentTimeInterval")
                        .HasColumnType("integer");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("endHour")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<bool>("isOffDay")
                        .HasColumnType("boolean");

                    b.Property<string>("startHour")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("id");

                    b.HasIndex("businessId", "date");

                    b.ToTable("BusinessWorkingInfo");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Campaign", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<string>("path")
                        .HasColumnType("text");

                    b.Property<int>("sortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("url")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.ToTable("Campaign");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Comment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("baseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<string>("comment")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("commentType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("point")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("updateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("userId", "businessId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Complain", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("userId", "businessId");

                    b.ToTable("Complain");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.ConfirmationInfo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("target")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.HasIndex("target", "code");

                    b.ToTable("ConfirmationInfo");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Favorite", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("userId");

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.PaymentInfo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("amount")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("isPaid")
                        .HasColumnType("boolean");

                    b.Property<int>("paidType")
                        .HasColumnType("integer");

                    b.Property<double>("payAmount")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("payDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("receiptFilePath")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("businessId", "paidType");

                    b.ToTable("PaymentInfo");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Services", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("className")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("colorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("nameEn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("sortOrder")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("birthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("city")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("fullName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("gender")
                        .HasColumnType("integer");

                    b.Property<string>("imageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("isBan")
                        .HasColumnType("boolean");

                    b.Property<string>("password")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("role")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("services")
                        .HasColumnType("text");

                    b.Property<string>("telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("updateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.HasIndex("email", "telephone");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Appointment", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany("appointments")
                        .HasForeignKey("businessId");

                    b.HasOne("CareGardenApiV1.Model.User", "user")
                        .WithMany("appointments")
                        .HasForeignKey("userId");

                    b.Navigation("business");

                    b.Navigation("user");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.BusinessGallery", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany("galleries")
                        .HasForeignKey("businessId");

                    b.Navigation("business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.BusinessProperties", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany("properties")
                        .HasForeignKey("businessId");

                    b.Navigation("business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.BusinessServiceModel", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany("services")
                        .HasForeignKey("businessId");

                    b.HasOne("CareGardenApiV1.Model.Services", "service")
                        .WithMany("businessServices")
                        .HasForeignKey("serviceId");

                    b.Navigation("business");

                    b.Navigation("service");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.BusinessWorkingInfo", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany("workingInfos")
                        .HasForeignKey("businessId");

                    b.Navigation("business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Campaign", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany()
                        .HasForeignKey("businessId");

                    b.Navigation("business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Comment", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany("comments")
                        .HasForeignKey("businessId");

                    b.HasOne("CareGardenApiV1.Model.User", "user")
                        .WithMany("comments")
                        .HasForeignKey("userId");

                    b.Navigation("business");

                    b.Navigation("user");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Complain", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany()
                        .HasForeignKey("businessId");

                    b.HasOne("CareGardenApiV1.Model.User", "user")
                        .WithMany("complains")
                        .HasForeignKey("userId");

                    b.Navigation("business");

                    b.Navigation("user");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Favorite", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany("favorites")
                        .HasForeignKey("businessId");

                    b.HasOne("CareGardenApiV1.Model.User", "user")
                        .WithMany("favorites")
                        .HasForeignKey("userId");

                    b.Navigation("business");

                    b.Navigation("user");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.PaymentInfo", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany("paymentInfos")
                        .HasForeignKey("businessId");

                    b.Navigation("business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Business", b =>
                {
                    b.Navigation("appointments");

                    b.Navigation("comments");

                    b.Navigation("favorites");

                    b.Navigation("galleries");

                    b.Navigation("paymentInfos");

                    b.Navigation("properties");

                    b.Navigation("services");

                    b.Navigation("workingInfos");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Services", b =>
                {
                    b.Navigation("businessServices");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.User", b =>
                {
                    b.Navigation("appointments");

                    b.Navigation("comments");

                    b.Navigation("complains");

                    b.Navigation("favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
