// <auto-generated />
using System;
using CareGardenApiV1.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareGardenApiV1.Migrations
{
    [DbContext(typeof(CareGardenApiDbContext))]
    [Migration("20240820211659_MigrationV1")]
    partial class MigrationV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Appointment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<string>("cancellationDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("endDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isGuest")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("startDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<double>("totalDiscountPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("totalPrice")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("updateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("userEmail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uuid");

                    b.Property<string>("userName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("userTelephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("startDate");

                    b.HasIndex("status");

                    b.HasIndex("userId");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.AppointmentDetail", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("appointmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessServiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("discountPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("price")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("workerId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("appointmentId");

                    b.HasIndex("businessServiceId");

                    b.HasIndex("workerId");

                    b.ToTable("AppointmentDetail");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Business", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("appointmentPeopleCount")
                        .HasColumnType("integer");

                    b.Property<int>("appointmentTimeInterval")
                        .HasColumnType("integer");

                    b.Property<string>("city")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("descriptionEn")
                        .HasColumnType("text");

                    b.Property<string>("district")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("hasNotification")
                        .HasColumnType("boolean");

                    b.Property<bool>("hasPromotion")
                        .HasColumnType("boolean");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("isFeatured")
                        .HasColumnType("boolean");

                    b.Property<double>("latitude")
                        .HasColumnType("double precision");

                    b.Property<Point>("location")
                        .HasColumnType("geometry (point)");

                    b.Property<string>("logoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("longitude")
                        .HasColumnType("double precision");

                    b.Property<bool>("mobileOrOnlineServiceOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("nameForUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("officialHolidayAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("province")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("serviceIds")
                        .HasColumnType("text");

                    b.Property<string>("telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("updateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("verified")
                        .HasColumnType("boolean");

                    b.Property<int>("workingGenderType")
                        .HasColumnType("integer");

                    b.Property<int>("workingSizeType")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("city");

                    b.HasIndex("email");

                    b.HasIndex("nameForUrl");

                    b.HasIndex("telephone");

                    b.ToTable("Business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.BusinessGallery", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<string>("imageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("isProfilePhoto")
                        .HasColumnType("boolean");

                    b.Property<bool>("isSliderPhoto")
                        .HasColumnType("boolean");

                    b.Property<string>("size")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<int>("sortOrder")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.ToTable("BusinessGallery");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.BusinessPayment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("amount")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("appointmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("id");

                    b.HasIndex("appointmentId");

                    b.HasIndex("businessId");

                    b.HasIndex("businessUserId");

                    b.HasIndex("date");

                    b.ToTable("BusinessPayment");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.BusinessProperties", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<string>("key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("value")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.ToTable("BusinessProperties");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.BusinessServiceModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<bool>("isPopular")
                        .HasColumnType("boolean");

                    b.Property<int>("maxDuration")
                        .HasColumnType("integer");

                    b.Property<int>("minDuration")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("nameEn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("price")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("serviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("spot")
                        .HasColumnType("text");

                    b.Property<string>("spotEn")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("serviceId");

                    b.ToTable("BusinessService");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.BusinessUser", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("birthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("fullName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("gender")
                        .HasColumnType("integer");

                    b.Property<bool>("hasNotification")
                        .HasColumnType("boolean");

                    b.Property<string>("imageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("isBan")
                        .HasColumnType("boolean");

                    b.Property<string>("password")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("role")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("updateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("email");

                    b.HasIndex("telephone");

                    b.ToTable("BusinessUser");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.BusinessWorkingInfo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<string>("fridayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("mondayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("officialHolidayAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("saturdayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("sundayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("thursdayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("tuesdayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("wednesdayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.ToTable("BusinessWorkingInfo");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Campaign", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("about")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("aboutEn")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<string>("condition")
                        .HasColumnType("text");

                    b.Property<string>("conditionEn")
                        .HasColumnType("text");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("expireDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<string>("path")
                        .HasColumnType("text");

                    b.Property<string>("pathEn")
                        .HasColumnType("text");

                    b.Property<int>("sortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("titleEn")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("updateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("url")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("isActive");

                    b.ToTable("Campaign");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Comment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("appointmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("aspectsOfPoint")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("aspectsOfWorkerPoint")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<string>("comment")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("commentType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isShowProfile")
                        .HasColumnType("boolean");

                    b.Property<double>("point")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("replyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("updateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uuid");

                    b.Property<double>("workerPoint")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.HasIndex("appointmentId");

                    b.HasIndex("businessId");

                    b.HasIndex("replyId");

                    b.HasIndex("userId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Complain", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("userId");

                    b.ToTable("Complain");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.ConfirmationInfo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("target")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.HasIndex("target");

                    b.ToTable("ConfirmationInfo");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Discount", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<string>("colorCode")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<double>("rate")
                        .HasColumnType("double precision");

                    b.Property<string>("serviceIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("isActive");

                    b.ToTable("Discount");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Faq", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("answer")
                        .HasColumnType("text");

                    b.Property<string>("answerEn")
                        .HasColumnType("text");

                    b.Property<string>("category")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("categoryEn")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("question")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("questionEn")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("sortOrder")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Faq");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Favorite", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("userId");

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Notification", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("descriptionEn")
                        .HasColumnType("text");

                    b.Property<bool>("isRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("publishDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("redirectId")
                        .HasColumnType("uuid");

                    b.Property<string>("redirectUrl")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("titleEn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("userId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.PaymentInfo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("amount")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("isPaid")
                        .HasColumnType("boolean");

                    b.Property<int>("paidType")
                        .HasColumnType("integer");

                    b.Property<double>("payAmount")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("payDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("receiptFilePath")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("isPaid");

                    b.HasIndex("paidType");

                    b.ToTable("PaymentInfo");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.ResetLink", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("linkId")
                        .HasMaxLength(100)
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("email");

                    b.ToTable("ResetLink");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Services", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("className")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("colorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("nameEn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("sortOrder")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Setting", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.Property<string>("value")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("Setting");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("birthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("city")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("fullName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("gender")
                        .HasColumnType("integer");

                    b.Property<bool>("hasNotification")
                        .HasColumnType("boolean");

                    b.Property<string>("imageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("isBan")
                        .HasColumnType("boolean");

                    b.Property<double?>("latitude")
                        .HasColumnType("double precision");

                    b.Property<Point>("location")
                        .HasColumnType("geometry (point)");

                    b.Property<double?>("longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("password")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("role")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("services")
                        .HasColumnType("text");

                    b.Property<string>("telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("updateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.HasIndex("email");

                    b.HasIndex("telephone");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Worker", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("about")
                        .HasColumnType("text");

                    b.Property<string>("aboutEn")
                        .HasColumnType("text");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("createdUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("fridayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("mondayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("name")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("path")
                        .HasColumnType("text");

                    b.Property<string>("saturdayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("serviceIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sundayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("thursdayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("titleEn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("tuesdayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("wednesdayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("isActive");

                    b.ToTable("Worker");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.WorkerServicePrice", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessServiceId")
                        .HasColumnType("uuid");

                    b.Property<double>("price")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("workerId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("businessServiceId");

                    b.HasIndex("workerId");

                    b.ToTable("WorkerServicePrice");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Appointment", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.TableModel.Business", "business")
                        .WithMany("appointments")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Appointment_Business_businessId");

                    b.HasOne("CareGardenApiV1.Model.TableModel.User", "user")
                        .WithMany("appointments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Appointment_User_userId");

                    b.Navigation("business");

                    b.Navigation("user");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.AppointmentDetail", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.TableModel.Appointment", "appointment")
                        .WithMany("details")
                        .HasForeignKey("appointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_AppointmentDetail_Appointment_appointmentId");

                    b.HasOne("CareGardenApiV1.Model.TableModel.BusinessServiceModel", "businessService")
                        .WithMany("appointmentDetails")
                        .HasForeignKey("businessServiceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_AppointmentDetail_BusinessService_businessServiceId");

                    b.HasOne("CareGardenApiV1.Model.TableModel.Worker", "worker")
                        .WithMany("appointmentDetails")
                        .HasForeignKey("workerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_AppointmentDetail_Worker_workerId");

                    b.Navigation("appointment");

                    b.Navigation("businessService");

                    b.Navigation("worker");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.BusinessGallery", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.TableModel.Business", "business")
                        .WithMany("galleries")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_BusinessGallery_Business_businessId");

                    b.Navigation("business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.BusinessPayment", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.TableModel.Appointment", "appointment")
                        .WithMany("businessPayments")
                        .HasForeignKey("appointmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_BusinessPayment_Appointment_appointmentId");

                    b.HasOne("CareGardenApiV1.Model.TableModel.Business", "business")
                        .WithMany("businessPayments")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_BusinessPayment_Business_businessId");

                    b.HasOne("CareGardenApiV1.Model.TableModel.BusinessUser", "businessUser")
                        .WithMany("businessPayments")
                        .HasForeignKey("businessUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_BusinessPayment_BusinessUser_businessUserId");

                    b.Navigation("appointment");

                    b.Navigation("business");

                    b.Navigation("businessUser");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.BusinessProperties", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.TableModel.Business", "business")
                        .WithMany("properties")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_BusinessProperties_Business_businessId");

                    b.Navigation("business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.BusinessServiceModel", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.TableModel.Business", "business")
                        .WithMany("services")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_BusinessService_Business_businessId");

                    b.HasOne("CareGardenApiV1.Model.TableModel.Services", "service")
                        .WithMany("businessServices")
                        .HasForeignKey("serviceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_BusinessService_Services_serviceId");

                    b.Navigation("business");

                    b.Navigation("service");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.BusinessUser", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.TableModel.Business", "business")
                        .WithMany("businessUsers")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_BusinessUsers_Business_businessId");

                    b.Navigation("business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.BusinessWorkingInfo", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.TableModel.Business", "business")
                        .WithMany("workingInfos")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_BusinessWorkingInfo_Business_businessId");

                    b.Navigation("business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Campaign", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.TableModel.Business", "business")
                        .WithMany("campaigns")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Campaign_Business_businessId");

                    b.Navigation("business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Comment", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.TableModel.Appointment", "appointment")
                        .WithMany("comments")
                        .HasForeignKey("appointmentId");

                    b.HasOne("CareGardenApiV1.Model.TableModel.Business", "business")
                        .WithMany("comments")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Comment_Business_businessId");

                    b.HasOne("CareGardenApiV1.Model.TableModel.Comment", "reply")
                        .WithMany()
                        .HasForeignKey("replyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Comment_Comment_replyId");

                    b.HasOne("CareGardenApiV1.Model.TableModel.User", "user")
                        .WithMany("comments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Comment_User_userId");

                    b.Navigation("appointment");

                    b.Navigation("business");

                    b.Navigation("reply");

                    b.Navigation("user");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Complain", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.TableModel.Business", "business")
                        .WithMany("complains")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Complain_Business_businessId");

                    b.HasOne("CareGardenApiV1.Model.TableModel.User", "user")
                        .WithMany("complains")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Complain_User_userId");

                    b.Navigation("business");

                    b.Navigation("user");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Discount", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.TableModel.Business", "business")
                        .WithMany("discounts")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Discount_Business_businessId");

                    b.Navigation("business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Favorite", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.TableModel.Business", "business")
                        .WithMany("favorites")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Favorite_Business_businessId");

                    b.HasOne("CareGardenApiV1.Model.TableModel.User", "user")
                        .WithMany("favorites")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Favorite_User_userId");

                    b.Navigation("business");

                    b.Navigation("user");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Notification", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.TableModel.Business", "business")
                        .WithMany("notifications")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Notification_Business_businessId");

                    b.HasOne("CareGardenApiV1.Model.TableModel.User", "user")
                        .WithMany("notifications")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Notification_User_userId");

                    b.Navigation("business");

                    b.Navigation("user");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.PaymentInfo", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.TableModel.Business", "business")
                        .WithMany("paymentInfos")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_PaymentInfo_Business_businessId");

                    b.Navigation("business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Worker", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.TableModel.Business", "business")
                        .WithMany("workers")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Worker_Business_businessId");

                    b.Navigation("business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.WorkerServicePrice", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.TableModel.BusinessServiceModel", "businessService")
                        .WithMany("workerServicePrices")
                        .HasForeignKey("businessServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_WorkerServicePrices_BusinessService_businessServiceId");

                    b.HasOne("CareGardenApiV1.Model.TableModel.Worker", "worker")
                        .WithMany("workerServicePrices")
                        .HasForeignKey("workerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_WorkerServicePrices_Worker_workerId");

                    b.Navigation("businessService");

                    b.Navigation("worker");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Appointment", b =>
                {
                    b.Navigation("businessPayments");

                    b.Navigation("comments");

                    b.Navigation("details");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Business", b =>
                {
                    b.Navigation("appointments");

                    b.Navigation("businessPayments");

                    b.Navigation("businessUsers");

                    b.Navigation("campaigns");

                    b.Navigation("comments");

                    b.Navigation("complains");

                    b.Navigation("discounts");

                    b.Navigation("favorites");

                    b.Navigation("galleries");

                    b.Navigation("notifications");

                    b.Navigation("paymentInfos");

                    b.Navigation("properties");

                    b.Navigation("services");

                    b.Navigation("workers");

                    b.Navigation("workingInfos");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.BusinessServiceModel", b =>
                {
                    b.Navigation("appointmentDetails");

                    b.Navigation("workerServicePrices");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.BusinessUser", b =>
                {
                    b.Navigation("businessPayments");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Services", b =>
                {
                    b.Navigation("businessServices");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.User", b =>
                {
                    b.Navigation("appointments");

                    b.Navigation("comments");

                    b.Navigation("complains");

                    b.Navigation("favorites");

                    b.Navigation("notifications");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.TableModel.Worker", b =>
                {
                    b.Navigation("appointmentDetails");

                    b.Navigation("workerServicePrices");
                });
#pragma warning restore 612, 618
        }
    }
}
