// <auto-generated />
using System;
using CareGardenApiV1.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareGardenApiV1.Migrations
{
    [DbContext(typeof(CareGardenApiDbContext))]
    [Migration("20240515080021_CareGardenV34")]
    partial class CareGardenV34
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareGardenApiV1.Model.Appointment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("endDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("startDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<double>("totalDiscountPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("totalPrice")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("updateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("userId", "businessId", "startDate", "status");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.AppointmentDetail", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("appointmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessServiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("discountPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("price")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("workerId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("businessServiceId");

                    b.HasIndex("workerId");

                    b.HasIndex("appointmentId", "workerId");

                    b.ToTable("AppointmentDetail");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Business", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("appointmentPeopleCount")
                        .HasColumnType("integer");

                    b.Property<int>("appointmentTimeInterval")
                        .HasColumnType("integer");

                    b.Property<string>("city")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("descriptionEn")
                        .HasColumnType("text");

                    b.Property<string>("district")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("hasNotification")
                        .HasColumnType("boolean");

                    b.Property<bool>("hasPromotion")
                        .HasColumnType("boolean");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("isFeatured")
                        .HasColumnType("boolean");

                    b.Property<double>("latitude")
                        .HasColumnType("double precision");

                    b.Property<Point>("location")
                        .HasColumnType("geometry (point)");

                    b.Property<string>("logoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("officialHolidayAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("password")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("province")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("updateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("verified")
                        .HasColumnType("boolean");

                    b.Property<int>("workingGenderType")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("email", "telephone", "city");

                    b.ToTable("Business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.BusinessGallery", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<string>("imageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("isProfilePhoto")
                        .HasColumnType("boolean");

                    b.Property<bool>("isSliderPhoto")
                        .HasColumnType("boolean");

                    b.Property<string>("size")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<int>("sortOrder")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.ToTable("BusinessGallery");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.BusinessProperties", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<string>("key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("value")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.ToTable("BusinessProperties");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.BusinessServiceModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<bool>("isPopular")
                        .HasColumnType("boolean");

                    b.Property<int>("maxDuration")
                        .HasColumnType("integer");

                    b.Property<int>("minDuration")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("nameEn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("price")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("serviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("spot")
                        .HasColumnType("text");

                    b.Property<string>("spotEn")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("serviceId");

                    b.ToTable("BusinessService");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.BusinessWorkingInfo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<string>("fridayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("mondayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("officialHolidayAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("saturdayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("sundayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("thursdayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("tuesdayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("wednesdayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.ToTable("BusinessWorkingInfo");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Campaign", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("about")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("aboutEn")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<string>("condition")
                        .HasColumnType("text");

                    b.Property<string>("conditionEn")
                        .HasColumnType("text");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("expireDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<string>("path")
                        .HasColumnType("text");

                    b.Property<string>("pathEn")
                        .HasColumnType("text");

                    b.Property<int>("sortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("titleEn")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("updateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("url")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.ToTable("Campaign");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Comment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<string>("comment")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("commentType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("point")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("replyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("updateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("replyId");

                    b.HasIndex("userId", "businessId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Complain", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("userId", "businessId");

                    b.ToTable("Complain");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.ConfirmationInfo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("target")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.HasIndex("target", "code");

                    b.ToTable("ConfirmationInfo");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Discount", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<string>("colorCode")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<double>("rate")
                        .HasColumnType("double precision");

                    b.Property<string>("serviceIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("businessId", "isActive");

                    b.ToTable("Discount");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Faq", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("answer")
                        .HasColumnType("text");

                    b.Property<string>("answerEn")
                        .HasColumnType("text");

                    b.Property<string>("category")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("categoryEn")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("question")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("questionEn")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("sortOrder")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Faq");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Favorite", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("userId");

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Notification", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("descriptionEn")
                        .HasColumnType("text");

                    b.Property<bool>("isRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("publishDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("redirectId")
                        .HasColumnType("uuid");

                    b.Property<string>("redirectUrl")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("titleEn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.HasIndex("userId", "businessId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.PaymentInfo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("amount")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("isPaid")
                        .HasColumnType("boolean");

                    b.Property<int>("paidType")
                        .HasColumnType("integer");

                    b.Property<double>("payAmount")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("payDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("receiptFilePath")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("businessId", "paidType");

                    b.ToTable("PaymentInfo");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Services", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("className")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("colorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("nameEn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("sortOrder")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Setting", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.Property<string>("value")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("Setting");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("birthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("city")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("fullName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("gender")
                        .HasColumnType("integer");

                    b.Property<bool>("hasNotification")
                        .HasColumnType("boolean");

                    b.Property<string>("imageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("isBan")
                        .HasColumnType("boolean");

                    b.Property<double?>("latitude")
                        .HasColumnType("double precision");

                    b.Property<Point>("location")
                        .HasColumnType("geometry (point)");

                    b.Property<double?>("longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("password")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("role")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("services")
                        .HasColumnType("text");

                    b.Property<string>("telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("updateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.HasIndex("email", "telephone");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Worker", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("businessId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("createdUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("fridayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("mondayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("name")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("path")
                        .HasColumnType("text");

                    b.Property<string>("saturdayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("serviceIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sundayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("thursdayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("titleEn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("tuesdayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("wednesdayWorkHours")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("id");

                    b.HasIndex("businessId");

                    b.ToTable("Worker");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Appointment", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany("appointments")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Appointment_Business_businessId");

                    b.HasOne("CareGardenApiV1.Model.User", "user")
                        .WithMany("appointments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Appointment_User_userId");

                    b.Navigation("business");

                    b.Navigation("user");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.AppointmentDetail", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Appointment", "appointment")
                        .WithMany("details")
                        .HasForeignKey("appointmentId");

                    b.HasOne("CareGardenApiV1.Model.BusinessServiceModel", "businessService")
                        .WithMany()
                        .HasForeignKey("businessServiceId");

                    b.HasOne("CareGardenApiV1.Model.Worker", "worker")
                        .WithMany()
                        .HasForeignKey("workerId");

                    b.Navigation("appointment");

                    b.Navigation("businessService");

                    b.Navigation("worker");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.BusinessGallery", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany("galleries")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_BusinessGallery_Business_businessId");

                    b.Navigation("business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.BusinessProperties", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany("properties")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_BusinessProperties_Business_businessId");

                    b.Navigation("business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.BusinessServiceModel", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany("services")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_BusinessService_Business_businessId");

                    b.HasOne("CareGardenApiV1.Model.Services", "service")
                        .WithMany("businessServices")
                        .HasForeignKey("serviceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_BusinessService_Services_serviceId");

                    b.Navigation("business");

                    b.Navigation("service");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.BusinessWorkingInfo", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany("workingInfos")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_BusinessWorkingInfo_Business_businessId");

                    b.Navigation("business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Campaign", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany("campaigns")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Campaign_Business_businessId");

                    b.Navigation("business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Comment", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany("comments")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Comment_Business_businessId");

                    b.HasOne("CareGardenApiV1.Model.Comment", "reply")
                        .WithMany()
                        .HasForeignKey("replyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Comment_Comment_replyId");

                    b.HasOne("CareGardenApiV1.Model.User", "user")
                        .WithMany("comments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Comment_User_userId");

                    b.Navigation("business");

                    b.Navigation("reply");

                    b.Navigation("user");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Complain", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany("complains")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Complain_Business_businessId");

                    b.HasOne("CareGardenApiV1.Model.User", "user")
                        .WithMany("complains")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Complain_User_userId");

                    b.Navigation("business");

                    b.Navigation("user");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Discount", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany("discounts")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Discount_Business_businessId");

                    b.Navigation("business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Favorite", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany("favorites")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Favorite_Business_businessId");

                    b.HasOne("CareGardenApiV1.Model.User", "user")
                        .WithMany("favorites")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Favorite_User_userId");

                    b.Navigation("business");

                    b.Navigation("user");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Notification", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany()
                        .HasForeignKey("businessId");

                    b.HasOne("CareGardenApiV1.Model.User", "user")
                        .WithMany()
                        .HasForeignKey("userId");

                    b.Navigation("business");

                    b.Navigation("user");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.PaymentInfo", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany("paymentInfos")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_PaymentInfo_Business_businessId");

                    b.Navigation("business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Worker", b =>
                {
                    b.HasOne("CareGardenApiV1.Model.Business", "business")
                        .WithMany("workers")
                        .HasForeignKey("businessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Worker_Business_businessId");

                    b.Navigation("business");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Appointment", b =>
                {
                    b.Navigation("details");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Business", b =>
                {
                    b.Navigation("appointments");

                    b.Navigation("campaigns");

                    b.Navigation("comments");

                    b.Navigation("complains");

                    b.Navigation("discounts");

                    b.Navigation("favorites");

                    b.Navigation("galleries");

                    b.Navigation("paymentInfos");

                    b.Navigation("properties");

                    b.Navigation("services");

                    b.Navigation("workers");

                    b.Navigation("workingInfos");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.Services", b =>
                {
                    b.Navigation("businessServices");
                });

            modelBuilder.Entity("CareGardenApiV1.Model.User", b =>
                {
                    b.Navigation("appointments");

                    b.Navigation("comments");

                    b.Navigation("complains");

                    b.Navigation("favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
