//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareGardenApiV1.Resource {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CareGardenApiV1.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ConfirmationCodeMessageInOneMinute {
            get {
                return ResourceManager.GetString("ConfirmationCodeMessageInOneMinute", resourceCulture);
            }
        }
        
        public static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        public static string ElasticIndexlemeIslemiBasladi {
            get {
                return ResourceManager.GetString("ElasticIndexlemeIslemiBasladi", resourceCulture);
            }
        }
        
        public static string ValidNameMessage {
            get {
                return ResourceManager.GetString("ValidNameMessage", resourceCulture);
            }
        }
        
        public static string ValidEmailMessage {
            get {
                return ResourceManager.GetString("ValidEmailMessage", resourceCulture);
            }
        }
        
        public static string ValidMailOrTelephoneMessage {
            get {
                return ResourceManager.GetString("ValidMailOrTelephoneMessage", resourceCulture);
            }
        }
        
        public static string ValidTelephoneMessage {
            get {
                return ResourceManager.GetString("ValidTelephoneMessage", resourceCulture);
            }
        }
        
        public static string FeedbackSend {
            get {
                return ResourceManager.GetString("FeedbackSend", resourceCulture);
            }
        }
        
        public static string FeedbackNotSend {
            get {
                return ResourceManager.GetString("FeedbackNotSend", resourceCulture);
            }
        }
        
        public static string UserNotFoundEnteredMail {
            get {
                return ResourceManager.GetString("UserNotFoundEnteredMail", resourceCulture);
            }
        }
        
        public static string RegisteredUserEnteredMail {
            get {
                return ResourceManager.GetString("RegisteredUserEnteredMail", resourceCulture);
            }
        }
        
        public static string BusinessNotFoundEnteredMail {
            get {
                return ResourceManager.GetString("BusinessNotFoundEnteredMail", resourceCulture);
            }
        }
        
        public static string UserFoundEnteredTelephone {
            get {
                return ResourceManager.GetString("UserFoundEnteredTelephone", resourceCulture);
            }
        }
        
        public static string BusinessFoundEnteredTelephone {
            get {
                return ResourceManager.GetString("BusinessFoundEnteredTelephone", resourceCulture);
            }
        }
        
        public static string UserNotFoundEnteredInfo {
            get {
                return ResourceManager.GetString("UserNotFoundEnteredInfo", resourceCulture);
            }
        }
        
        public static string BusinessNotFoundEnteredInfo {
            get {
                return ResourceManager.GetString("BusinessNotFoundEnteredInfo", resourceCulture);
            }
        }
        
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        public static string RecordNotUpdated {
            get {
                return ResourceManager.GetString("RecordNotUpdated", resourceCulture);
            }
        }
        
        public static string CurrentPasswordNotCorrectly {
            get {
                return ResourceManager.GetString("CurrentPasswordNotCorrectly", resourceCulture);
            }
        }
        
        public static string Weekday {
            get {
                return ResourceManager.GetString("Weekday", resourceCulture);
            }
        }
        
        public static string Weekend {
            get {
                return ResourceManager.GetString("Weekend", resourceCulture);
            }
        }
        
        public static string IdErrorMessage {
            get {
                return ResourceManager.GetString("IdErrorMessage", resourceCulture);
            }
        }
        
        public static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        public static string RegistrationSuccess {
            get {
                return ResourceManager.GetString("RegistrationSuccess", resourceCulture);
            }
        }
        
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        public static string RecordDeleted {
            get {
                return ResourceManager.GetString("RecordDeleted", resourceCulture);
            }
        }
        
        public static string RecordNotDeleted {
            get {
                return ResourceManager.GetString("RecordNotDeleted", resourceCulture);
            }
        }
        
        public static string RegistrationFailed {
            get {
                return ResourceManager.GetString("RegistrationFailed", resourceCulture);
            }
        }
        
        public static string RecordExists {
            get {
                return ResourceManager.GetString("RecordExists", resourceCulture);
            }
        }
        
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        public static string ConfirmationCodeNotVerified {
            get {
                return ResourceManager.GetString("ConfirmationCodeNotVerified", resourceCulture);
            }
        }
        
        public static string ConfirmationCodeVerified {
            get {
                return ResourceManager.GetString("ConfirmationCodeVerified", resourceCulture);
            }
        }
        
        public static string ConfirmationCodeSend {
            get {
                return ResourceManager.GetString("ConfirmationCodeSend", resourceCulture);
            }
        }
        
        public static string ConfirmationCodeNotSend {
            get {
                return ResourceManager.GetString("ConfirmationCodeNotSend", resourceCulture);
            }
        }
        
        public static string ConfirmationCodeExpired {
            get {
                return ResourceManager.GetString("ConfirmationCodeExpired", resourceCulture);
            }
        }
        
        public static string ConfirmationMessage {
            get {
                return ResourceManager.GetString("ConfirmationMessage", resourceCulture);
            }
        }
        
        public static string PopularServices {
            get {
                return ResourceManager.GetString("PopularServices", resourceCulture);
            }
        }
        
        public static string AppointmentCancelWarning {
            get {
                return ResourceManager.GetString("AppointmentCancelWarning", resourceCulture);
            }
        }
        
        public static string ColorCodeErrorMessage {
            get {
                return ResourceManager.GetString("ColorCodeErrorMessage", resourceCulture);
            }
        }
        
        public static string ImageUploaded {
            get {
                return ResourceManager.GetString("ImageUploaded", resourceCulture);
            }
        }
        
        public static string PasswordMustBeEightCharacters {
            get {
                return ResourceManager.GetString("PasswordMustBeEightCharacters", resourceCulture);
            }
        }
        
        public static string PasswordsMustBeEqual {
            get {
                return ResourceManager.GetString("PasswordsMustBeEqual", resourceCulture);
            }
        }
        
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        public static string ResetPasswordSuccess {
            get {
                return ResourceManager.GetString("ResetPasswordSuccess", resourceCulture);
            }
        }
        
        public static string ResetPasswordFailed {
            get {
                return ResourceManager.GetString("ResetPasswordFailed", resourceCulture);
            }
        }
        
        public static string ResetPasswordMailMessage {
            get {
                return ResourceManager.GetString("ResetPasswordMailMessage", resourceCulture);
            }
        }
        
        public static string ResetPasswordMessage {
            get {
                return ResourceManager.GetString("ResetPasswordMessage", resourceCulture);
            }
        }
        
        public static string BusinessNotFound {
            get {
                return ResourceManager.GetString("BusinessNotFound", resourceCulture);
            }
        }
        
        public static string NotPermission {
            get {
                return ResourceManager.GetString("NotPermission", resourceCulture);
            }
        }
        
        public static string AppointmentAvailable {
            get {
                return ResourceManager.GetString("AppointmentAvailable", resourceCulture);
            }
        }
        
        public static string Anonymous {
            get {
                return ResourceManager.GetString("Anonymous", resourceCulture);
            }
        }
        
        public static string ConfirmationCodeForAppointment {
            get {
                return ResourceManager.GetString("ConfirmationCodeForAppointment", resourceCulture);
            }
        }
        
        public static string BusinessNotVerified {
            get {
                return ResourceManager.GetString("BusinessNotVerified", resourceCulture);
            }
        }
        
        public static string BusinessVerified {
            get {
                return ResourceManager.GetString("BusinessVerified", resourceCulture);
            }
        }
        
        public static string AppointmentCancelled {
            get {
                return ResourceManager.GetString("AppointmentCancelled", resourceCulture);
            }
        }
        
        public static string AppointmentNotCancelled {
            get {
                return ResourceManager.GetString("AppointmentNotCancelled", resourceCulture);
            }
        }
        
        public static string AppointmentStatusChanged {
            get {
                return ResourceManager.GetString("AppointmentStatusChanged", resourceCulture);
            }
        }
        
        public static string AppointmentStatusNotChanged {
            get {
                return ResourceManager.GetString("AppointmentStatusNotChanged", resourceCulture);
            }
        }
        
        public static string ErrorContactMessage {
            get {
                return ResourceManager.GetString("ErrorContactMessage", resourceCulture);
            }
        }
        
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        public static string ImageNotUploaded {
            get {
                return ResourceManager.GetString("ImageNotUploaded", resourceCulture);
            }
        }
        
        public static string RecordUpdated {
            get {
                return ResourceManager.GetString("RecordUpdated", resourceCulture);
            }
        }
        
        public static string BusinessFoundEnteredMail {
            get {
                return ResourceManager.GetString("BusinessFoundEnteredMail", resourceCulture);
            }
        }
        
        public static string UserFoundEnteredMail {
            get {
                return ResourceManager.GetString("UserFoundEnteredMail", resourceCulture);
            }
        }
        
        public static string AllMessagesRead {
            get {
                return ResourceManager.GetString("AllMessagesRead", resourceCulture);
            }
        }
        
        public static string RecordsDeleted {
            get {
                return ResourceManager.GetString("RecordsDeleted", resourceCulture);
            }
        }
        
        public static string RecordsNotDeleted {
            get {
                return ResourceManager.GetString("RecordsNotDeleted", resourceCulture);
            }
        }
        
        public static string LocationNotUpdated {
            get {
                return ResourceManager.GetString("LocationNotUpdated", resourceCulture);
            }
        }
        
        public static string LocationUpdated {
            get {
                return ResourceManager.GetString("LocationUpdated", resourceCulture);
            }
        }
        
        public static string LoginFailedUserMessage {
            get {
                return ResourceManager.GetString("LoginFailedUserMessage", resourceCulture);
            }
        }
        
        public static string WorkerPriceErrorMessage {
            get {
                return ResourceManager.GetString("WorkerPriceErrorMessage", resourceCulture);
            }
        }
        
        public static string PasswordResetLinkExpired {
            get {
                return ResourceManager.GetString("PasswordResetLinkExpired", resourceCulture);
            }
        }
        
        public static string PasswordResetLinkMessage {
            get {
                return ResourceManager.GetString("PasswordResetLinkMessage", resourceCulture);
            }
        }
        
        public static string PasswordResetLinkMessageInOneHour {
            get {
                return ResourceManager.GetString("PasswordResetLinkMessageInOneHour", resourceCulture);
            }
        }
        
        public static string PasswordResetLinkNotFound {
            get {
                return ResourceManager.GetString("PasswordResetLinkNotFound", resourceCulture);
            }
        }
        
        public static string PasswordResetLinkNotSend {
            get {
                return ResourceManager.GetString("PasswordResetLinkNotSend", resourceCulture);
            }
        }
        
        public static string PasswordResetLinkSend {
            get {
                return ResourceManager.GetString("PasswordResetLinkSend", resourceCulture);
            }
        }
        
        public static string StartDateNotBiggerEndDate {
            get {
                return ResourceManager.GetString("StartDateNotBiggerEndDate", resourceCulture);
            }
        }
        
        public static string DateMaxRangeError {
            get {
                return ResourceManager.GetString("DateMaxRangeError", resourceCulture);
            }
        }
    }
}
