//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareGardenApiV1.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CareGardenApiV1.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir dakika içinde birden fazla onay kodu alamazsınız..
        /// </summary>
        public static string BirDakikaIcindeOnayKoduMesaji {
            get {
                return ResourceManager.GetString("BirDakikaIcindeOnayKoduMesaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu alanı boş bırakmayınız..
        /// </summary>
        public static string BuAlaniBosBirakmayiniz {
            get {
                return ResourceManager.GetString("BuAlaniBosBirakmayiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elastic indexleme işlemi arkaplanda başlamıştır..
        /// </summary>
        public static string ElasticIndexlemeIslemiBasladi {
            get {
                return ResourceManager.GetString("ElasticIndexlemeIslemiBasladi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elastic server is not active..
        /// </summary>
        public static string ElasticSunucusuAktifDegil {
            get {
                return ResourceManager.GetString("ElasticSunucusuAktifDegil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçerli bir isim giriniz..
        /// </summary>
        public static string GecerliBirIsimGiriniz {
            get {
                return ResourceManager.GetString("GecerliBirIsimGiriniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir mail giriniz..
        /// </summary>
        public static string GecerliMailMesaji {
            get {
                return ResourceManager.GetString("GecerliMailMesaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir mail veya telefon numarası giriniz..
        /// </summary>
        public static string GecerliMailTelefonMesaji {
            get {
                return ResourceManager.GetString("GecerliMailTelefonMesaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir telefon numarası giriniz..
        /// </summary>
        public static string GecerliTelefonMesaji {
            get {
                return ResourceManager.GetString("GecerliTelefonMesaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your feedback..
        /// </summary>
        public static string GeriBildirimGonderildi {
            get {
                return ResourceManager.GetString("GeriBildirimGonderildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz maile ait kullanıcı bulunamadı..
        /// </summary>
        public static string GirdiginizMaileAitKullaniciBulunamadi {
            get {
                return ResourceManager.GetString("GirdiginizMaileAitKullaniciBulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz maile ait kullanıcı sistemde kayıtlı..
        /// </summary>
        public static string GirdiginizMaileAitKullaniciKayitli {
            get {
                return ResourceManager.GetString("GirdiginizMaileAitKullaniciKayitli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz maile ait şirket bulunamadı..
        /// </summary>
        public static string GirdiginizMaileAitSirketBulunamadi {
            get {
                return ResourceManager.GetString("GirdiginizMaileAitSirketBulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz telefon numarasına ait kullanıcı sistemde kayıtlı..
        /// </summary>
        public static string GirdiginizTelefonNumarasinaAitKullaniciKayitli {
            get {
                return ResourceManager.GetString("GirdiginizTelefonNumarasinaAitKullaniciKayitli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company belonging to the phone number you entered is registered in the system..
        /// </summary>
        public static string GirdiginizTelefonNumarasinaAitSirketKayitli {
            get {
                return ResourceManager.GetString("GirdiginizTelefonNumarasinaAitSirketKayitli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girilen bilgilere ait kullanıcı bulunamadı..
        /// </summary>
        public static string GirilenBilgilereAitKullaniciBulunamadi {
            get {
                return ResourceManager.GetString("GirilenBilgilereAitKullaniciBulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girilen bilgilere ait şirket bulunamadı..
        /// </summary>
        public static string GirilenBilgilereAitSirketBulunamadi {
            get {
                return ResourceManager.GetString("GirilenBilgilereAitSirketBulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş başarılı..
        /// </summary>
        public static string GirisBasarili {
            get {
                return ResourceManager.GetString("GirisBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş yapılamadı..
        /// </summary>
        public static string GirisYapilamadi {
            get {
                return ResourceManager.GetString("GirisYapilamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelleme yapılamadı..
        /// </summary>
        public static string GuncellemeYapilamadi {
            get {
                return ResourceManager.GetString("GuncellemeYapilamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncel şifrenizi doğru giriniz..
        /// </summary>
        public static string GuncelSifreniziDogruGiriniz {
            get {
                return ResourceManager.GetString("GuncelSifreniziDogruGiriniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hafta içi.
        /// </summary>
        public static string HaftaIci {
            get {
                return ResourceManager.GetString("HaftaIci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hafta sonu.
        /// </summary>
        public static string HaftaSonu {
            get {
                return ResourceManager.GetString("HaftaSonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılan istekte geçerli bir id gönderilmedi..
        /// </summary>
        public static string IdParametreHatasi {
            get {
                return ResourceManager.GetString("IdParametreHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% indirim.
        /// </summary>
        public static string Indirim {
            get {
                return ResourceManager.GetString("Indirim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarılı bir şekilde tamamlandı..
        /// </summary>
        public static string KayitBasarili {
            get {
                return ResourceManager.GetString("KayitBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt bulunamadı..
        /// </summary>
        public static string KayitBulunamadi {
            get {
                return ResourceManager.GetString("KayitBulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt silindi..
        /// </summary>
        public static string KayitSilindi {
            get {
                return ResourceManager.GetString("KayitSilindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt silinemedi..
        /// </summary>
        public static string KayitSilinemedi {
            get {
                return ResourceManager.GetString("KayitSilinemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt yapılamadı..
        /// </summary>
        public static string KayitYapilamadi {
            get {
                return ResourceManager.GetString("KayitYapilamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı bulunamadi..
        /// </summary>
        public static string KullaniciBulunamadi {
            get {
                return ResourceManager.GetString("KullaniciBulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay kodu doğrulanamadı..
        /// </summary>
        public static string OnayKoduDogrulanamadi {
            get {
                return ResourceManager.GetString("OnayKoduDogrulanamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay kodu doğrulandı..
        /// </summary>
        public static string OnayKoduDogrulandi {
            get {
                return ResourceManager.GetString("OnayKoduDogrulandi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay kodu gönderildi..
        /// </summary>
        public static string OnayKoduGonderildi {
            get {
                return ResourceManager.GetString("OnayKoduGonderildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay kodu gönderilemedi..
        /// </summary>
        public static string OnayKoduGonderilemedi {
            get {
                return ResourceManager.GetString("OnayKoduGonderilemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay kodu zaman aşımına uğradı. Lütfen yeniden kod isteyin..
        /// </summary>
        public static string OnayKoduZamanAsiminaUgradi {
            get {
                return ResourceManager.GetString("OnayKoduZamanAsiminaUgradi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CareGarden&apos; a hoşgeldin. Onay Kodu : {0}.
        /// </summary>
        public static string OnayMesaji {
            get {
                return ResourceManager.GetString("OnayMesaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popüler Servisler.
        /// </summary>
        public static string PopulerServisler {
            get {
                return ResourceManager.GetString("PopulerServisler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randevuya 9 saat kala randevuyu iptal etmek güvenilirliğinizi azaltır. İptal etmek istiyor musunuz?.
        /// </summary>
        public static string RandevuIptalUyari {
            get {
                return ResourceManager.GetString("RandevuIptalUyari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renk kodu 3 veya 6 haneli olmalı..
        /// </summary>
        public static string RenkKoduHatasi {
            get {
                return ResourceManager.GetString("RenkKoduHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim başarılı bir şekilde yüklendi. .
        /// </summary>
        public static string ResimYuklemeBasarili {
            get {
                return ResourceManager.GetString("ResimYuklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre en az 8 karakter olmalı..
        /// </summary>
        public static string Sifre8KarakterOlmali {
            get {
                return ResourceManager.GetString("Sifre8KarakterOlmali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreler eşit olmalı..
        /// </summary>
        public static string SifrelerEsitOlmali {
            get {
                return ResourceManager.GetString("SifrelerEsitOlmali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Yenileme.
        /// </summary>
        public static string SifreYenileme {
            get {
                return ResourceManager.GetString("SifreYenileme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre yenileme işlemi başarılı..
        /// </summary>
        public static string SifreYenilemeBasarili {
            get {
                return ResourceManager.GetString("SifreYenilemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre yenilemedi..
        /// </summary>
        public static string SifreYenilemedi {
            get {
                return ResourceManager.GetString("SifreYenilemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre yenileme işlemi için onay kodu {0}..
        /// </summary>
        public static string SifreYenilemeMailMesaji {
            get {
                return ResourceManager.GetString("SifreYenilemeMailMesaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrenizi unuttuysanız şifremi unuttum kısmından şifrenizi yenileyebilirsiniz..
        /// </summary>
        public static string SifreYenilemeMesaji {
            get {
                return ResourceManager.GetString("SifreYenilemeMesaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket bulunamadı..
        /// </summary>
        public static string SirketBulunamadi {
            get {
                return ResourceManager.GetString("SirketBulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkiniz yok..
        /// </summary>
        public static string YetkinizYok {
            get {
                return ResourceManager.GetString("YetkinizYok", resourceCulture);
            }
        }
    }
}
