//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareGardenApiV1.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CareGardenApiV1.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm mesajlar okundu olarak işaretlendi..
        /// </summary>
        public static string AllMessagesRead {
            get {
                return ResourceManager.GetString("AllMessagesRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonim.
        /// </summary>
        public static string Anonymous {
            get {
                return ResourceManager.GetString("Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz tarihte bir randevu alındığı için randevu yapılamadı. Lütfen başka bir tarih seçerek tekrar deneyiniz..
        /// </summary>
        public static string AppointmentAvailable {
            get {
                return ResourceManager.GetString("AppointmentAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randevu başarıyla iptal edildi..
        /// </summary>
        public static string AppointmentCancelled {
            get {
                return ResourceManager.GetString("AppointmentCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randevuya 9 saat kala randevuyu iptal etmek, güvenilirliğinizi azaltabilir. İptal etmek istiyor musunuz?.
        /// </summary>
        public static string AppointmentCancelWarning {
            get {
                return ResourceManager.GetString("AppointmentCancelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randevunun iptal edilmesi sırasında bir hata oluştu..
        /// </summary>
        public static string AppointmentNotCancelled {
            get {
                return ResourceManager.GetString("AppointmentNotCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randevunun durumu başarıyla güncellendi..
        /// </summary>
        public static string AppointmentStatusChanged {
            get {
                return ResourceManager.GetString("AppointmentStatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randevunun durumu güncellenirken bir hata oluştu..
        /// </summary>
        public static string AppointmentStatusNotChanged {
            get {
                return ResourceManager.GetString("AppointmentStatusNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz e-posta adresine ait kayıtlı bir işletme bulunmaktadır..
        /// </summary>
        public static string BusinessFoundEnteredMail {
            get {
                return ResourceManager.GetString("BusinessFoundEnteredMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz telefon numarasına kayıtlı bir işletme bulunmaktadır..
        /// </summary>
        public static string BusinessFoundEnteredTelephone {
            get {
                return ResourceManager.GetString("BusinessFoundEnteredTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşletme bulunamadı..
        /// </summary>
        public static string BusinessNotFound {
            get {
                return ResourceManager.GetString("BusinessNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz bilgilere ait bir işletme bulunamadı..
        /// </summary>
        public static string BusinessNotFoundEnteredInfo {
            get {
                return ResourceManager.GetString("BusinessNotFoundEnteredInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz e-posta adresine ait işletme bulunamadı..
        /// </summary>
        public static string BusinessNotFoundEnteredMail {
            get {
                return ResourceManager.GetString("BusinessNotFoundEnteredMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşletme doğrulanamadı..
        /// </summary>
        public static string BusinessNotVerified {
            get {
                return ResourceManager.GetString("BusinessNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşletme doğrulandı..
        /// </summary>
        public static string BusinessVerified {
            get {
                return ResourceManager.GetString("BusinessVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renk kodu 3 veya 6 haneli olmalı..
        /// </summary>
        public static string ColorCodeErrorMessage {
            get {
                return ResourceManager.GetString("ColorCodeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay kodunun süresi doldu. Lütfen yeni bir kod isteyin..
        /// </summary>
        public static string ConfirmationCodeExpired {
            get {
                return ResourceManager.GetString("ConfirmationCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randevuyu tamamlamak için onay kodu {0}..
        /// </summary>
        public static string ConfirmationCodeForAppointment {
            get {
                return ResourceManager.GetString("ConfirmationCodeForAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir dakika içinde birden fazla onay kodu alamazsınız..
        /// </summary>
        public static string ConfirmationCodeMessageInOneMinute {
            get {
                return ResourceManager.GetString("ConfirmationCodeMessageInOneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay kodu gönderilemedi..
        /// </summary>
        public static string ConfirmationCodeNotSend {
            get {
                return ResourceManager.GetString("ConfirmationCodeNotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay kodu doğrulanamadı..
        /// </summary>
        public static string ConfirmationCodeNotVerified {
            get {
                return ResourceManager.GetString("ConfirmationCodeNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay kodu gönderildi..
        /// </summary>
        public static string ConfirmationCodeSend {
            get {
                return ResourceManager.GetString("ConfirmationCodeSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay kodu doğrulandı..
        /// </summary>
        public static string ConfirmationCodeVerified {
            get {
                return ResourceManager.GetString("ConfirmationCodeVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CareGarden&apos; a hoşgeldiniz! Onay Kodu : {0}.
        /// </summary>
        public static string ConfirmationMessage {
            get {
                return ResourceManager.GetString("ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen güncel şifrenizi doğru giriniz..
        /// </summary>
        public static string CurrentPasswordNotCorrectly {
            get {
                return ResourceManager.GetString("CurrentPasswordNotCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih aralağı maximum bir ay olmalıdır..
        /// </summary>
        public static string DateMaxRangeError {
            get {
                return ResourceManager.GetString("DateMaxRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elastic indexleme işlemi arkaplanda başlamıştır..
        /// </summary>
        public static string ElasticIndexlemeIslemiBasladi {
            get {
                return ResourceManager.GetString("ElasticIndexlemeIslemiBasladi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen daha sonra tekrar deneyiniz veya destek ekibimizle iletişime geçiniz..
        /// </summary>
        public static string ErrorContactMessage {
            get {
                return ResourceManager.GetString("ErrorContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir hata oluştu..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri bildirim gönderilemedi..
        /// </summary>
        public static string FeedbackNotSend {
            get {
                return ResourceManager.GetString("FeedbackNotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri bildiriminiz gönderildi. Teşekkür ederiz!.
        /// </summary>
        public static string FeedbackSend {
            get {
                return ResourceManager.GetString("FeedbackSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçerli bir id gönderilmediğinden dolayı istek işlenemedi..
        /// </summary>
        public static string IdErrorMessage {
            get {
                return ResourceManager.GetString("IdErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim yüklenirken bir hata oluştu..
        /// </summary>
        public static string ImageNotUploaded {
            get {
                return ResourceManager.GetString("ImageNotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim başarılı bir şekilde yüklendi. .
        /// </summary>
        public static string ImageUploaded {
            get {
                return ResourceManager.GetString("ImageUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konum bilginiz güncellenirken bir hata oluştu..
        /// </summary>
        public static string LocationNotUpdated {
            get {
                return ResourceManager.GetString("LocationNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konum bilginiz güncellendi..
        /// </summary>
        public static string LocationUpdated {
            get {
                return ResourceManager.GetString("LocationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş yapılamadı..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz e-posta adresi veya parola hatalı..
        /// </summary>
        public static string LoginFailedUserMessage {
            get {
                return ResourceManager.GetString("LoginFailedUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş başarılı..
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu alanı boş bırakmayınız..
        /// </summary>
        public static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu işlemi gerçekleştirmek için yetkiniz yok. Lütfen gerekli izinler için sistem yöneticinizle iletişime geçiniz..
        /// </summary>
        public static string NotPermission {
            get {
                return ResourceManager.GetString("NotPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cilt analizi için belirlenen maksimum istek sınırına ulaştınız. Daha fazla analiz yapabilmek için bize ulaşın..
        /// </summary>
        public static string OpenAIRequestLimitMessage {
            get {
                return ResourceManager.GetString("OpenAIRequestLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI isteği gönderilemedi..
        /// </summary>
        public static string OpenAIRequestNotSend {
            get {
                return ResourceManager.GetString("OpenAIRequestNotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI isteği gönderildi..
        /// </summary>
        public static string OpenAIRequestSend {
            get {
                return ResourceManager.GetString("OpenAIRequestSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre en az 8 karakter olmalı..
        /// </summary>
        public static string PasswordMustBeEightCharacters {
            get {
                return ResourceManager.GetString("PasswordMustBeEightCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre sıfırlama bağlantısı süresi doldu. Lütfen bir şifre sıfırlama bağlantısı talep edin..
        /// </summary>
        public static string PasswordResetLinkExpired {
            get {
                return ResourceManager.GetString("PasswordResetLinkExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre yenileme işleminize devam etmek için &lt;a href=&apos;{0}&apos; target=&apos;_blank&apos;&gt;buraya&lt;/a&gt; tıklayabilirsiz..
        /// </summary>
        public static string PasswordResetLinkMessage {
            get {
                return ResourceManager.GetString("PasswordResetLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir saat içinde birden fazla şifre yenileme bağlantısı alamazsınız..
        /// </summary>
        public static string PasswordResetLinkMessageInOneHour {
            get {
                return ResourceManager.GetString("PasswordResetLinkMessageInOneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset link not found..
        /// </summary>
        public static string PasswordResetLinkNotFound {
            get {
                return ResourceManager.GetString("PasswordResetLinkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre yenileme bağlantısı gönderilemedi..
        /// </summary>
        public static string PasswordResetLinkNotSend {
            get {
                return ResourceManager.GetString("PasswordResetLinkNotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre yenileme bağlantısı gönderildi..
        /// </summary>
        public static string PasswordResetLinkSend {
            get {
                return ResourceManager.GetString("PasswordResetLinkSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz şifreler birbiriyle eşleşmiyor..
        /// </summary>
        public static string PasswordsMustBeEqual {
            get {
                return ResourceManager.GetString("PasswordsMustBeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popüler Servisler.
        /// </summary>
        public static string PopularServices {
            get {
                return ResourceManager.GetString("PopularServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarıyla silindi..
        /// </summary>
        public static string RecordDeleted {
            get {
                return ResourceManager.GetString("RecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kaydı zaten mevcut..
        /// </summary>
        public static string RecordExists {
            get {
                return ResourceManager.GetString("RecordExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt silinemedi..
        /// </summary>
        public static string RecordNotDeleted {
            get {
                return ResourceManager.GetString("RecordNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt bulunamadı..
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelleme işlemi yapılamadı..
        /// </summary>
        public static string RecordNotUpdated {
            get {
                return ResourceManager.GetString("RecordNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlar başarıyla silindi..
        /// </summary>
        public static string RecordsDeleted {
            get {
                return ResourceManager.GetString("RecordsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlar silinemedi..
        /// </summary>
        public static string RecordsNotDeleted {
            get {
                return ResourceManager.GetString("RecordsNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelleme işleminiz başarıyla tamamlandı..
        /// </summary>
        public static string RecordUpdated {
            get {
                return ResourceManager.GetString("RecordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belirttiğiniz e-posta adresi sistemimizde zaten kayıtlı. Lütfen farklı bir e-posta adresi giriniz veya mevcut hesabınıza giriş yapınız..
        /// </summary>
        public static string RegisteredUserEnteredMail {
            get {
                return ResourceManager.GetString("RegisteredUserEnteredMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt işlemi sırasında bir hata oluştu..
        /// </summary>
        public static string RegistrationFailed {
            get {
                return ResourceManager.GetString("RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt işleminiz başarıyla tamamlandı..
        /// </summary>
        public static string RegistrationSuccess {
            get {
                return ResourceManager.GetString("RegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Yenileme.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre yenileme işlemi başarısız oldu..
        /// </summary>
        public static string ResetPasswordFailed {
            get {
                return ResourceManager.GetString("ResetPasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre yenileme işlemi için onay kodu {0}..
        /// </summary>
        public static string ResetPasswordMailMessage {
            get {
                return ResourceManager.GetString("ResetPasswordMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğer şifrenizi unuttuysanız, &apos;Şifremi Unuttum&apos; seçeneğini kullanarak şifrenizi yenileyebilirsiniz.
        /// </summary>
        public static string ResetPasswordMessage {
            get {
                return ResourceManager.GetString("ResetPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre yenileme işlemi başarıyla tamamlandı..
        /// </summary>
        public static string ResetPasswordSuccess {
            get {
                return ResourceManager.GetString("ResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% indirim.
        /// </summary>
        public static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç tarihi bitiş tarihinin büyük olamaz..
        /// </summary>
        public static string StartDateNotBiggerEndDate {
            get {
                return ResourceManager.GetString("StartDateNotBiggerEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz e-posta adresine ait bir kullanıcı bulunmaktadır..
        /// </summary>
        public static string UserFoundEnteredMail {
            get {
                return ResourceManager.GetString("UserFoundEnteredMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz telefon numarasına kayıtlı bir kullanıcı bulunmaktadır..
        /// </summary>
        public static string UserFoundEnteredTelephone {
            get {
                return ResourceManager.GetString("UserFoundEnteredTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı bulunamadı..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz bilgilere ait bir kullanıcı bulunamadı..
        /// </summary>
        public static string UserNotFoundEnteredInfo {
            get {
                return ResourceManager.GetString("UserNotFoundEnteredInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz e-posta adresine ait kullanıcı bulunamadı..
        /// </summary>
        public static string UserNotFoundEnteredMail {
            get {
                return ResourceManager.GetString("UserNotFoundEnteredMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir mail giriniz..
        /// </summary>
        public static string ValidEmailMessage {
            get {
                return ResourceManager.GetString("ValidEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir e-posta adresi veya telefon numarası giriniz..
        /// </summary>
        public static string ValidMailOrTelephoneMessage {
            get {
                return ResourceManager.GetString("ValidMailOrTelephoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçerli bir isim giriniz..
        /// </summary>
        public static string ValidNameMessage {
            get {
                return ResourceManager.GetString("ValidNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir telefon numarası giriniz..
        /// </summary>
        public static string ValidTelephoneMessage {
            get {
                return ResourceManager.GetString("ValidTelephoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hafta içi.
        /// </summary>
        public static string Weekday {
            get {
                return ResourceManager.GetString("Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hafta sonu.
        /// </summary>
        public static string Weekend {
            get {
                return ResourceManager.GetString("Weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışana özel fiyat, servis fiyatından yüksek olamaz..
        /// </summary>
        public static string WorkerPriceErrorMessage {
            get {
                return ResourceManager.GetString("WorkerPriceErrorMessage", resourceCulture);
            }
        }
    }
}
